services:
  - type: web
    name: chess-io
    runtime: python
    buildCommand: pip install -r requirements.txt && apt-get install -y stockfish
    startCommand: gunicorn app:app -w 1 --threads 4 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
